### ISSUE TITLE
Workflow doesn't fetch data anymore

### ISSUE THREAD

**Issue by vadimvh** [loris/alfred-producthunt-workflow#1]
Hi Loris, looks like the workflow stopped fetching data from PH..

**Comment by loris** [comment]
Looks like my developer token was disabled (probably because someone used it for his its own purpose).
I will need to implement a proper OAuth authentification, probably in the coming days. Stay tuned.

**Comment by vadimvh** [comment]
I stay tuned ;)

**Comment by Overload119** [comment]
+1

**Comment by chrismessina** [comment]
Four months later... any updates?

**Comment by tejasmanohar** [comment]
New ProductHunt API is out http://www.producthunt.com/posts/product-hunt-api-beta

**Comment by cliffordfajardo** [comment]
Still doesn't fetch data

**Comment by chrismessina** [comment]
You'll need to register and get your own API key and then add it to the script settings.
![banners_and_alerts_and_alfred_preferences](https://cloud.githubusercontent.com/assets/22610/5620288/53a97254-94df-11e4-9f3e-88739d3734d9.png)

**Comment by cliffordfajardo** [comment]
Thanks!

**Comment by politicus** [comment]
Added my API key. Still no data fetched.

In Alfred console, I get this message:

``` html
[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "ph.py", line 11, in get_items
    data = json.loads(urllib2.urlopen(request).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

```

**Comment by chrismessina** [comment]
It's not working for me either. Maybe they broke the endpoint?

Your error suggests that your token isn't working though. Are you sure you copied it correctly from here?

https://www.producthunt.com/v1/oauth/applications

**Comment by politicus** [comment]
I installed this workflow a few months ago. Never really used it. Last week, I wanted to use it more, so I retested it. Checked I added an API key. It didn't work at all. I tried to add a new API key, went on the page you suggest, but to be honest, I didn't really understand what the require-uri meant. I tried "https://api.producthunt.com/v1/posts". I still got a similar error in the Alfred console.

As I maybe didn't add the right uri, I would rather say I can't make the workflow work than the workflow does not work.

**Comment by loris** [comment]
Hi all, sorry for the delay.
I have no idea why the dev token was being revoked so frequently (usage must be very low). Anyway, since it was not really clever to store my token in the client workflow, I put up a quick&dirty Node.js server ([source](https://github.com/loris/alfred-producthunt-workflow/blob/master/source/server/index.js)) hosted on Heroku to proxy (and pre-fetch) API calls to Product Hunt.
You should not have any problem related to API keys anymore (or at least, I will be able to fix it server-side now).

**Comment by politicus** [comment]
@loris Reinstalled the workflow. Working pretty well. Thank you!
